### ISSUE TITLE
Support for <paramref> and other XML elements in comments

### ISSUE THREAD

**Issue by stevegreatrex** [domaindrivendev/Swashbuckle#188] opened 2015-02-17 13:13 UTC
The XML comments feature is great but it would be even better if it supported XML sub-elements in the comments.

**Comment by tillig** [comment] 2015-02-27 14:57
Just for tracking purposes, this is somewhat a duplicate of #166.

**Comment by stevegreatrex** [comment] 2015-02-27 14:58
Yep, I just said the same (in reverse) over there!

**Closed** 2015-03-27 20:22 UTC
