### ISSUE TITLE
Swashbuckle doesn't display all controllers and all endpoints

### ISSUE THREAD

**Issue by mkrasser** [domaindrivendev/Swashbuckle#1058] opened 2017-05-01 22:41 UTC
I'm using Swashbuckle 5.5.3 with an asp.net WebApi project.  I can get the Swagger UI to display fine, but one of my controllers is not visible.  When I drill down into one the of the other controllers, it's displays 4 of 6 endpoints - missing 2.  Not sure how to fix this problem.

**Comment by heldersepu** [comment] 2017-05-02 14:52
I never encountered this issue before...
 can you post a link to your asp.net WebApi project

**Comment by mkrasser** [comment] 2017-05-02 16:23
I'm sorry, I'm not able to post a link to the project for security reasons.  I was able to get the missing controller to display just now be shortening the RoutePrefix for the controller.  Is there a max length on the RoutePrefix?  Any way to change this?

**Comment by mkrasser** [comment] 2017-05-02 17:19
Correction, the problem doesn't appear to be the length of the route, but the presence of special characters in the route.

The controller won't display if the route prefix is:
    [RoutePrefix("foos/{fooId}/bars/{barId}/widgets")]

It will display if I change it to:
       [RoutePrefix("foos/{fooId}/bars/barId/widgets")]

It seems to be having trouble with the second set of {}.

**Comment by heldersepu** [comment] 2017-05-02 17:50
Can you create a sample asp.net WebApi project reproducing your problem?

**Comment by heldersepu** [comment] 2017-05-02 18:25
After some reading on RoutePrefix & Route, I think you might be using it incorrectly...
Take a look at this controller
https://github.com/heldersepu/csharp-proj/blob/master/Swagger_Test/Swagger_Test/Controllers/RoutePrefixController.cs
The RoutePrefix is something common for all actions and the actions are those with the special characters

Nothing is missing:
http://swashbuckletest.azurewebsites.net/swagger/ui/index#/RoutePrefix

**Comment by mkrasser** [comment] 2017-05-02 20:09
Thanks, I'll check out these links.  I tried to repro the problem in another project and wasn't able to.  It must be something specific to my project then.

**Comment by mkrasser** [comment] 2017-05-02 20:37
I think I'm getting closer to the problem.  There's a custom binding attribute on the barId parameter.  I think something's wrong there.  That is the common link between the controller/endpoints that won't display.  I'll do some testing around this and see what I come up with.  Other custom bindings are used elsewhere and work fine, but this particular one seems to be a problem.

**Comment by mkrasser** [comment] 2017-05-02 22:31
I was able to repro the problem.  

    [RoutePrefix("foos/{fooId}/bars/{barId}/widgets")]
    public class FooController : ApiController
    {
        [HttpGet]
        [Route("")]
        public string Get(int id, [FooBinding]Models.FooId fooId)
        {
            return "value";
        }
    }

    public class FooBindingAttribute : ParameterBindingAttribute
    {
        public override HttpParameterBinding GetBinding(HttpParameterDescriptor parameter)
        {
            if (parameter.ParameterType != typeof(Models.FooId))
            {
                throw new ArgumentException("FooBinding is only valid for FooId parameters.", "parameter");
            }
            return new FooBinding(parameter);
        }
    }
    public class FooBinding : HttpParameterBinding
    {
        public const string FooIdRouteParameter = "fooId";
        public FooBinding(HttpParameterDescriptor descriptor)
            : base(descriptor)
        {
        }

        public override Task ExecuteBindingAsync(ModelMetadataProvider metadataProvider, HttpActionContext actionContext, CancellationToken cancellationToken)
        {
            Models.FooId result = null;
            var rawValue = actionContext.ControllerContext.RouteData.Values[FooIdRouteParameter] as string;
            result = new Models.FooId(rawValue);
            base.SetValue(actionContext, result);
            return Task.FromResult(true);
        }
    }

**Comment by heldersepu** [comment] 2017-05-02 23:54
I managed to reproduce without the external dependencies (Models.FooId) Here: 
https://github.com/heldersepu/csharp-proj/blob/master/Swagger_Test/Swagger_Test/Controllers/BindingController.cs

Now the real debugging can begin...

**Comment by heldersepu** [comment] 2017-05-04 02:19
I'm hitting a brick-wall here:
https://github.com/heldersepu/Swashbuckle/blob/1058_missing_enpoint/Swashbuckle.Core/Application/SwaggerDocsConfig.cs#L279

That ```httpConfig.Services.GetApiExplorer()``` is what gets all the paths, and unfortunately that is a from namespace System.Web.Http

**Comment by heldersepu** [comment] 2017-05-04 12:41
## Sorry but I'm giving up on this...

Here is my latest research:
http://swashbuckletest.azurewebsites.net/api/ApiExplorer
and here is the code for that controller:
https://github.com/heldersepu/csharp-proj/blob/master/Swagger_Test/Swagger_Test/Controllers/ApiExplorerController.cs

In that sample I'm using the ```Services.GetApiExplorer()``` and it is missing the GET from the BindingController:
https://github.com/heldersepu/csharp-proj/blob/master/Swagger_Test/Swagger_Test/Controllers/BindingController.cs

I guess if you want to follow up, next step will be to contact Microsoft see if they want to get to the bottom  of this issue...

**Comment by heldersepu** [comment] 2017-05-04 13:06
One last observation, See the code below:
```c#
using System.Web.Http;

namespace Swagger_Test.Controllers
{
    [RoutePrefix("attrib")]
    public class AttributeController : ApiController
    {
        [Route("{id}")]
        public void Post([FromUri]string id)
        {
        }
    }
}

```
with the ```[FromUri]``` it work fine, but if we change it to ```[FromBody]``` it no longer shows

**Comment by mkrasser** [comment] 2017-05-04 15:19
Ok, thanks.  I appreciate your efforts on this.  I continued to research this and it appears to be a problem with ApiExplorer() which is an asp.net thing.  I like the workaround of using [FromUri].  I'll do that. 
Thanks again!

**Comment by mkrasser** [comment] 2017-05-04 15:45
[FromUri] works great!

**Comment by heldersepu** [comment] 2017-05-04 15:47
Then we have an "official" workaround until MS fixes ApiExplorer, I think you can close this issue now.

**Closed** 2017-05-04 15:57 UTC

**Comment by commonsensesoftware** [comment] 2017-06-05 22:36
@heldersepu It seems you've done all that you could here. At least you were able to find a reasonable workaround. Unfortunately, I'm not able to see your repro. Maybe you took it down already. With regards to `[FromBody]`, it's pretty finicky about primitives (e.g. using `string`). Without the repro for you research, I feel I might be missing something.

@mkrasser based on the example you provided, I wouldn't even expect a request to match:

```c#
[RoutePrefix("foos/{fooId}/bars/{barId}/widgets")]
public class FooController : ApiController
{
    [HttpGet]
    [Route("")]
    public string Get(int id, [FooBinding]Models.FooId fooId)
    {
        return "value";
    }
}
```
The `id` parameter is not matched in the route template, although the intention implies that you expected it. The standard ASP.NET model binder will assume `[FromUri]` by default. Therefore, a request would only work if it was formed like: `/foos/ipitythefoo/bars/crobar/widgets?id=42`. The other odd thing is where is the `barId` parameter? Since it's in the path, it's required. Perhaps `id` was supposed to be `barId`?

The **IApiExplorer** in ASP.NET Web API is not so great. It's horrible to extend. To make it work for API Versioning, I had to [fork](https://github.com/Microsoft/aspnet-api-versioning/blob/master/src/Microsoft.AspNet.WebApi.Versioning.ApiExplorer/Description/VersionedApiExplorer.cs) its original source code. Worse still, it uses a number of internal-only types. I'll let you imagine the ensuing nightmare; it wasn't pretty. I haven't seen this specific issue, but it could be related to routing, configuration, or truly a bug in the API Explorer. It's design was kind of an afterthought. Fortunately, that's not the case in ASP.NET Core.

If you see this occur in the API Versioning implementation or discover more insight, do share. I'd rather not repeat the mistakes of old.

**Comment by heldersepu** [comment] 2017-06-05 23:05
@commonsensesoftware 
Sorry about that,  I did move my code, I just updated all the links...

**Comment by commonsensesoftware** [comment] 2017-06-05 23:42
I did a meager amount of research. This question/issue actually seems to be a duplicate of #518. Another workable solution was provided there. It's a little long and not worth reiterating here. I'd say that either that approach or the approach proposed here are the best options. Any other options and you are likely down in the bowels of the **IApiExplorer**. trying to change it.

One sleazy way you can extend the **IApiExlorer** is use the _Adapter_ pattern over it and then fix-up API descriptions before they get picked up by Swagger/Swashbuckle. It's still not ideal, but not a huge amount of work to do. Alternatively, you could just create an **IApiExplorer** implementation that imperatively lists all known APIs. This would be hard to maintain for large API sets, but it's doable.

Sorry, there no great answers here. Hopefully that provides some additional insight.
