### ISSUE TITLE
[Swashbuckle 5.1.4] Angle brackets in CDATA are encoded in Swagger

### ISSUE THREAD

**Issue by PeterZong** [domaindrivendev/Swashbuckle#454] opened 2015-08-12 08:27 UTC
Hi,

I added the following comments for my method. When I check my Swagger file, the angle brackets are encoded. However I don't want the "<" to be encoded to be &amp;lt;. What can I do?

Code:

        /// <remarks>
        /// <![CDATA[Create user. This is longer explanation how to use the 
        /// API. This description can contain <strong>rich</strong> <code>text</code> formatting.]]>
        /// </remarks>
        public void Post(User user) { }

The Swagger generated by Swashbuckle 5.1.4:

"description":"Create user. This is longer explanation how to use the \r\n            API. This description can contain &amp;lt;strong&amp;gt;rich&amp;lt;/strong&amp;gt; &amp;lt;code&amp;gt;text&amp;lt;/code&amp;gt; formatting."

Thanks,
Peter

**Comment by domaindrivendev** [comment] 2015-08-22 02:52
Correct me if I'm wrong but I think this is really a duplicate of #258 which is really just asking for better support to add richer markup in the description fields

**Closed by domaindrivendev** 2015-08-22 02:52 UTC

**Comment by davetransom** [comment] 2015-09-10 04:07
Shouldn't this be written _as_ markdown? e.g.

    /// Create user. This is longer explanation how to use the 
    /// API. This description can contain **rich** `text` formatting.
