### ISSUE TITLE
oauth scopes added as comma separated strings not space separated strings

### ISSUE THREAD

**Issue by chrisdostert** [domaindrivendev/Swashbuckle#230] opened 2015-03-12 19:43 UTC
When using oauth2 per https://github.com/domaindrivendev/Swashbuckle/blob/master/Swashbuckle.Dummy.Core/App_Start/SwaggerConfig.cs#l83-87

the scope parameter when sent to the oauth2 server will be comma separated strings which is invalid; they must be space separated per https://tools.ietf.org/html/rfc6749#section-3.3
"The value of the scope parameter is expressed as a list of space-
   delimited[...]"

**Comment by svrooij** [comment] 2015-03-29 15:35
@chrisdostert this seems to be a problem of the included swagger-ui source.

Because this problem is fixed in the 2.0 version of swagger ui. We just have to wait for the developer of swashbuckle to pull the latest version of Swagger-ui into this project.

**Comment by chrisdostert** [comment] 2015-03-31 19:40
@svrooij how do you know it is a problem with swagger-ui ?

**Comment by svrooij** [comment] 2015-03-31 19:49
@chrisdostert because I created an issue on the swagger-ui repo about this bug and got an aw set they fixed it. https://github.com/swagger-api/swagger-ui/issues/1031

**Comment by chrisdostert** [comment] 2015-03-31 19:49
@svrooij ahh.. you're right; after looking at the source it looks like swagger-ui is simply pulling the claims from the raw swagger spec natively; I was under the incorrect assumption swashbuckle was doing custom magic with the swagger-ui assets.

**Comment by domaindrivendev** [comment] 2015-04-02 07:18
Should be fixed with latest (pre-release) version ...

    Update-Package Swashbuckle -Pre

**Closed by domaindrivendev** 2015-04-02 07:18 UTC

**Comment by nickverschueren** [comment] 2015-10-22 13:36
In the latest stable version 5.2.2 there seems to be regression on this. Scopes are again comma seperated, not space separated when using the included swagger-ui.
