### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by Gentlehag** [domaindrivendev/Swashbuckle#272] opened 2015-04-14 10:07 UTC
In one project i got a nullrefrenceException   with the followign stacktrace

is there a way to get the element which causes the problem?

500 : {"Message":"An error has occurred.","ExceptionMessage":"Object reference not set to an instance of an object.","ExceptionType":"System.NullReferenceException","StackTrace":" at Swashbuckle.Swagger.XmlComments.ApplyXmlTypeComments.ApplyPropertyComments(Schema propertySchema, MemberInfo memberInfo)\r\n at Swashbuckle.Swagger.XmlComments.ApplyXmlTypeComments.Apply(Schema model, ModelFilterContext context)\r\n at Swashbuckle.Swagger.SchemaRegistry.CreateObjectSchema(JsonObjectContract jsonContract)\r\n at Swashbuckle.Swagger.SchemaRegistry.GetOrRegister(Type type)\r\n at Swashbuckle.Swagger.SwaggerGenerator.CreateOperation(ApiDescription apiDescription, SchemaRegistry schemaRegistry)\r\n at Swashbuckle.Swagger.SwaggerGenerator.CreatePathItem(IEnumerable`1 apiDescriptions, SchemaRegistry schemaRegistry)\r\n at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)\r\n at Swashbuckle.Swagger.SwaggerGenerator.GetSwagger(String rootUrl, String apiVersion)\r\n at Swashbuckle.Application.SwaggerDocsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\r\n at System.Net.Http.HttpMessageInvoker.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\r\n at System.Web.Http.Dispatcher.HttpRoutingDispatcher.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\r\n at System.Web.Http.Tracing.Tracers.RequestMessageHandlerTracer.<>c__DisplayClass4.b__1()\r\n at System.Web.Http.Tracing.ITraceWriterExtensions.TraceBeginEndAsync[TResult](ITraceWriter traceWriter, HttpRequestMessage request, String category, TraceLevel level, String operatorName, String operationName, Action`1 beginTrace, Func`1 execute, Action`2 endTrace, Action`1 errorTrace)\r\n at System.Web.Http.Tracing.Tracers.RequestMessageHandlerTracer.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)\r\n at System.Web.Http.HttpServer.d__0.MoveNext()"} http://localhost:80/Booking/swagger/docs/v1

**Comment by domaindrivendev** [comment] 2015-04-14 16:17
This is a duplicate of #270, which should now be fixed with the latest release - 5.1.2.

It's worth noting that there is currently no support for using Xml comments from public fields. This fix simply prevents the null reference exception from occurring but leaves the description blank.

Full support will be added at some point

**Closed by domaindrivendev** 2015-04-14 16:17 UTC

**Comment by Gentlehag** [comment] 2015-04-15 06:29
Confirmed. Update helped
