### ISSUE TITLE
Cannot read property 'getMockSignature' of undefined

### ISSUE THREAD

**Issue by dmitriynosenko** [domaindrivendev/Swashbuckle#100] opened 2014-10-07 13:53 UTC
Hello. I am trying to add Swagger docs for WebAPI project. Once swagger page loads I am getting tons of error:
```javascript
Uncaught TypeError: Cannot read property 'getMockSignature' of undefined swagger.js line 782.
```
If you'll open this file on this line you'll see 
```javascript
return models[listType].getMockSignature();
```
I saw that listType in my case could be String or Boolean, but models array doesn't contains record for such types.
How to fix this issue? Maybe my configuration is wrong?
Thanks!

**Comment by domaindrivendev** [comment] 2015-01-22 07:25
I tried the latest stable version of swagger-ui and noticed the issue is still there. However, it appears to be  fixed in their latest "alpha" version (v2.1.0-alpha.4) which is currently embedded with Swashbuckle 5.0 Alpha. If you're willing to make the upgrade, your issue should be resolved.

    Install-Package Swashbuckle -Pre

You can read up more on Swashbuckle 5.0 Alpha (including a transition guide) here - https://github.com/domaindrivendev/Swashbuckle/tree/swagger_2.0

**Closed by domaindrivendev** 2015-01-22 07:25 UTC
