### ISSUE TITLE
Swashbuckle is not presenting properties' descriptions for properties with JsonProperty(PropertyName) set.

### ISSUE THREAD

**Issue by lwojtal1** [domaindrivendev/Swashbuckle#238] opened 2015-03-18 09:38 UTC
I am generating swagger documentation from xml auto-generated from comments. When a property of my schema class is decorated with [JsonProperty(PropertyName = "...")], the property's comment/description is not being shown.
Example:
public class MySchema
{
        /// <summary>
        /// Field desc
        /// </summary>
       public string Field { get; set; }
}
displays model in UI as:
MySchema {
Field (string, optional): Field desc
}
Which is OK. But when I add JsonProperty:
public class MySchema
{
        /// <summary>
        /// Field desc
        /// </summary>
       [JsonProperty(PropertyName="f")]
       public string Field { get; set; }
}
The property's description is missing:
MySchema {
f (string, optional)
}

**Comment by aphu** [comment] 2015-03-19 16:33
The problem is Swashbuckle looks at your JsonProperty that you set and compares it to your xml document file. For your last example, if you have a property name of "f" and your property is called "Field", Swashbuckle will look for "f" in your xml file which it won't find since it doesn't exist. What you can do is have all your JsonProperty property name match all your variables. I made a pull request to fix this but it hasn't been merged yet. Hope that helps.

**Comment by micheltol** [comment] 2015-03-23 11:07
HI, this solution works fine if every first character  is unique in your model.
If I would have a model like: 

    public class MySample{
    [JsonProperty(PropertyName="S")]
    public string Status { get; set; }

    [JsonProperty(PropertyName="C")]
    public string Score { get; set; }
}

this solution wouldn't work.
I think it would be a better solution if you could give Swashbuckle an optional instruction which comment/description belong to which json property. How to do that, I wouldn;t have a clue yet :)

**Comment by domaindrivendev** [comment] 2015-04-02 07:19
Should be fixed with the latest (pre-release) version

    Update-Package Swashbuckle -Pre

**Closed by domaindrivendev** 2015-04-02 07:19 UTC
