### ISSUE TITLE
Getting CORS Error

### ISSUE THREAD

**Issue by ravi032** [domaindrivendev/Swashbuckle#354] opened 2015-05-22 05:47 UTC
Error Screenshot:

![swagger](https://cloud.githubusercontent.com/assets/9535992/7764769/bcd216f0-0073-11e5-8096-a23b3dac490b.JPG)

I am trying to access swagger document details from differently hosted swagger ui app. Kindly check screenshot attache. I get message "Can't read from server. It may not have the appropriate access-control-origin settings.". Kindly let me know where can I do necessary changes to overcome to it?

**Comment by dmyers** [comment] 2015-05-27 17:38
Duplicate of #329

**Comment by ambassadorJ** [comment] 2015-05-28 04:27
In the Web.Config of localhost:80, add the following to the `<system.webServer>` section
```Web.Config
    <httpProtocol>
      <customHeaders>
        <add name="Access-Control-Allow-Origin" value="*" />
      </customHeaders>
    </httpProtocol>
```

**Closed** 2015-05-31 00:56 UTC
