### ISSUE TITLE
5.0 Request and response Models not supported for array of complex types

### ISSUE THREAD

**Issue by amanzoor** [domaindrivendev/Swashbuckle#200] opened 2015-02-20 16:46 UTC
Request Model Issues: So when upgrading to 5.0 I noticed that my request model of type array object don't show up any more, rather the swagger UI shows them as the actual string value of the corresponding schema in the swagger json. Interestingly enough array of objects that are properties inside another object show up properly. Case in point:

For PUT for a collection of ListItemDtos the swagger UI shows up incorrectly as:

![image](https://cloud.githubusercontent.com/assets/2073235/6289706/d24bed24-b8d6-11e4-95e6-7265804a5d54.png)

On the other hand PUT for a linked list for the swagger UI shows up correctly as:

![image](https://cloud.githubusercontent.com/assets/2073235/6289828/c21c8eb2-b8d7-11e4-830a-480a3363d723.png)

Response Model Issue: For the response models of the same type the problem is not that bad, The response model shows up but it only shows up as the type of the array with no indication whatsoever that it is a collection of the type, which can be confusing for the consumers of the API.  Case in point: 

For the GET for a collection of list items, the response model incorrectly only shows a single item:

![image](https://cloud.githubusercontent.com/assets/2073235/6304922/a0bcb7ba-b8dc-11e4-929c-bfe726c86b45.png)

The model schema on the other hand is accurate:

![image](https://cloud.githubusercontent.com/assets/2073235/6304951/c66c5e66-b8dc-11e4-82a8-bbebe78dad7c.png)

Is this a known issue? I hope we can address this quickly as it is a big impediment for releasing the next version of our API to customers.

Thanks - Auzeb

**Comment by domaindrivendev** [comment] 2015-02-23 17:24
Hi there

As the underlying Swagger json generated by SB appears to be correct, these are really issues with the [swagger-ui](https://github.com/swagger-api/swagger-ui) - an upstream dependency of SB.

I'll open a ticket there that references this one and as soon as a fix is available, I'll update SB to pull in the fixed version

**Comment by amanzoor** [comment] 2015-02-23 18:45
Great, thanks!

**Comment by fehguy** [comment] 2015-02-24 15:03
hi @amanzoor @domaindrivendev will look into this shortly.  If you can please share the JSON that is being rendered by the API it would help speed up the fix & corresponding tests.

**Comment by amanzoor** [comment] 2015-02-24 18:07
{
  "swagger": "2.0",
  "info": {
    "version": "v3",
    "title": "Version 3 of the Public Safety API"
  },
  "host": "dev-api.local:80",
  "schemes": [
    "http"
  ],
  "paths": {
    "/v3/lists/{listId}": {
      "get": {
        "tags": [
          "Lists"
        ],
        "summary": "Get a list by its identifier",
        "description": "Gets a list by its identifier",
        "operationId": "Lists_GetListByListId",
        "consumes": [],
        "produces": [
          "application/json",
          "text/json",
          "application/xml",
          "text/xml"
        ],
        "parameters": [
          {
            "name": "listId",
            "in": "path",
            "description": "the identifier for the list",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/ListItemDto"
              }
            }
          }
        },
        "deprecated": false
      },
      "put": {
        "tags": [
          "Lists"
        ],
        "summary": "Update a list",
        "operationId": "Lists_PutUpdatesList",
        "consumes": [
          "application/json",
          "text/json",
          "application/xml",
          "text/xml",
          "application/x-www-form-urlencoded"
        ],
        "produces": [
          "application/json",
          "text/json",
          "application/xml",
          "text/xml"
        ],
        "parameters": [
          {
            "name": "listId",
            "in": "path",
            "description": "The identifier for the list",
            "required": true,
            "type": "string"
          },
          {
            "name": "dtos",
            "in": "body",
            "description": "A collection of list items",
            "required": true,
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/ListItemDto"
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/SaveListResponseDto"
            }
          }
        },
        "deprecated": false
      }
    }
  },
  "definitions": {
    "ListItemDto": {
      "required": [
        "PrimaryCode",
        "Description"
      ],
      "type": "object",
      "properties": {
        "PrimaryCode": {
          "type": "string"
        },
        "SecondaryCode": {
          "type": "string"
        },
        "Description": {
          "type": "string"
        },
        "Hidden": {
          "type": "boolean"
        }
      }
    },
    "SaveListResponseDto": {
      "type": "object",
      "properties": {
        "Version": {
          "format": "int32",
          "type": "integer"
        },
        "Data": {
          "type": "array",
          "items": {
            "$ref": "ListItemDto"
          }
        },
        "LastModifiedTimestamp": {
          "type": "string"
        }
      }
    }
  }
}

**Comment by amanzoor** [comment] 2015-02-24 18:08
Above is the json for the API with the 2 methods illustrating the issues for both request and response models.

**Comment by fehguy** [comment] 2015-02-25 07:18
Thanks @amanzoor.  

For issue 1, can you please tell me the version of the swagger-ui library?  You should see something at the top of swagger-ui.js

For your 2nd issue, This is actually by design.  The `model` section shows the components that go into an input or response.  It doesn't try to show them in the exact structure.  The `model schema` will show the appropriate content.

**Comment by amanzoor** [comment] 2015-02-25 16:09
I believe its v2.1.5-M1. I pulled down the latest packge update for swasbuckle that includes v2.1.5-M1 . 

The latest version shows the response model as array { } now instead of the model that is an item in the array.  I think that this might confusing for the consumers of the api because for complex types that are not arrays the model shows up accurately but for collections of complex types it just shows up as array {} :

![image](https://cloud.githubusercontent.com/assets/2073235/6374211/52040236-bcc4-11e4-9fc6-fb344c3e62ab.png)

vs 

![image](https://cloud.githubusercontent.com/assets/2073235/6374433/a6895166-bcc5-11e4-957e-a085633e8fca.png)

**Comment by fehguy** [comment] 2015-02-25 16:14
Please try to manually update swagger ui to 2.1.8-M1. I believe this issue has been fixed post 2.1.5-M1

**Comment by amanzoor** [comment] 2015-02-25 16:20
I will try it on my own here. @domaindrivendev can you please update swashbuckle to version 2.1.8-M1

**Comment by domaindrivendev** [comment] 2015-02-25 17:09
Still seeing this in 2.1.8-M1

![version](https://cloud.githubusercontent.com/assets/1434343/6375730/d3bee486-bccd-11e4-9e43-3ef7b33d9ba7.png)

![array-param](https://cloud.githubusercontent.com/assets/1434343/6375732/d90b178e-bccd-11e4-93e4-f74c554ba1f2.png)

Also, the response description of array {} now shows no model information

![array-response](https://cloud.githubusercontent.com/assets/1434343/6375751/f7af7a86-bccd-11e4-8b1f-bc7d9a77c7aa.png)

**Comment by amanzoor** [comment] 2015-02-26 18:08
@fehguy I have the same issue

**Comment by amanzoor** [comment] 2015-03-09 21:38
@fehguy any update on a fix for this?

**Comment by gnomyvw** [comment] 2015-03-10 10:16
Same issue here. Very interested in a fix for this too.

**Comment by amanzoor** [comment] 2015-03-11 17:41
I will have to revert to the older version of swagger/swashbuckle since there have been no activity on this and we have delayed releasing our documentation long enough, it sucks since I really liked the the new version. Hopefully this gets addressed soon.

**Comment by fehguy** [comment] 2015-03-11 20:12
There needs to be an issue tracked in swagger-ui.  @whitlockjc and @mohsen1 are working on this right now.  Sorry if it feels too slow, but we are in the midst of a fairly big commit right now.

**Comment by amanzoor** [comment] 2015-03-11 20:55
I though there was an issue for it already. Do you need me to create one? and if it is being worked on, that's great! Can I get a rough ETA on it? if its by the end of the week for example, I would rather wait than revert to the older version. Thanks!

**Comment by whitlockjc** [comment] 2015-03-11 21:36
I'll be working on this by end of day.  No official ETA but I'm hoping to get this done by end of week.

**Comment by amanzoor** [comment] 2015-03-11 22:24
Thanks for the update!

**Comment by amanzoor** [comment] 2015-03-18 20:05
@whitlockjc Hey, any update on a fix for this?

**Comment by whitlockjc** [comment] 2015-03-18 20:43
It's my current task but I just started today.  M2 releases end of week, last I heard, so I'm hoping to have it done by then.

**Comment by amanzoor** [comment] 2015-03-23 17:53
@whitlockjc Has a fix been released for it?

**Comment by whitlockjc** [comment] 2015-03-23 18:07
Partly but it's unreleased.

**Comment by amanzoor** [comment] 2015-03-23 20:55
any idea when you would be done? I dont want to wait if it is going to more than a few days. Thanks

**Comment by whitlockjc** [comment] 2015-03-26 01:29
This just landed in the `develop_2.0` branch.  I'm starting to add more tests for things so if you find something, let me know.

**Comment by amanzoor** [comment] 2015-03-30 16:03
Sweet, will try it out

**Comment by fehguy** [comment] 2015-03-30 17:00
FYI swagger-ui-2.1.0-M2 was released today.  It's available in npmjs.org and shortly will be a proper release in the swagger-ui repo.

**Comment by fehguy** [comment] 2015-03-30 17:56
Please see here:

https://github.com/swagger-api/swagger-ui/releases/tag/v2.1.0-M2

**Comment by amanzoor** [comment] 2015-03-30 18:58
So I tried 2.1.0-M2 out and it seems to have fixed one of the issues i.e. the $ref in the response model is resolved to the correct object structure, but the parameter  data types for a request operation still seems to be mapping as ref. Case in point:
![image](https://cloud.githubusercontent.com/assets/2073235/6904023/1612c5ea-d6d3-11e4-891a-266b22e80179.png)
The above response model is being mapped correctly

![image](https://cloud.githubusercontent.com/assets/2073235/6904060/5c4ead8a-d6d3-11e4-975b-76726f7fa74e.png)

The above request operation parameter ref is not being mapped/resolved. 

I am not sure if this issue is still outstanding, my understanding was that the 2 issues were related and the milestone list seems to suggest that it has benn fixed. @domaindrivendev can you please verify this (I used the debug configuration to test this inside swashbuckle and upgraded the embedded swagger-ui to the latest commit on master).

**Comment by domaindrivendev** [comment] 2015-04-01 16:40
Just put out a pre-release version of SB (5.1.0-rc1) with the latest swagger-ui ...

As demonstrated above by @amanzoor, the latest swagger-ui still doesn't display array parameters correctly.

@whitlockjc, @fehguy - is this a known issue or should we create another issue in the repo?

**Comment by whitlockjc** [comment] 2015-04-01 17:21
Looks like it might be related to this in swagger-js: [lib/types/operation.js#L290](https://github.com/swagger-api/swagger-js/blob/develop_2.0/lib/types/operation.js#L290)  It's an easy fix but it was not addressed when we fixed how models and arrays of models were displayed in the response.  I'll file the bug for you.

**Comment by whitlockjc** [comment] 2015-04-01 17:26
Did I summarize things properly?

**Comment by domaindrivendev** [comment] 2015-04-01 17:52
Sounds good - thx

**Comment by domaindrivendev** [comment] 2015-06-30 16:17
This is fixed with the latest swagger-ui release - 2.1.0.

It's now merged into SB and just awaiting release

**Comment by amanzoor** [comment] 2015-06-30 18:05
Cool, thanks!

**Comment by domaindrivendev** [comment] 2015-07-15 15:11
Released

**Closed by domaindrivendev** 2015-07-15 15:11 UTC
Labels: Ready for release
