### ISSUE TITLE
ApiKey in header not working

### ISSUE THREAD

**Issue by tinman-chad** [domaindrivendev/Swashbuckle#275] opened 2015-04-16 15:50 UTC
Setting the apikey details in the SwaggerConfig.cs for an api key in the header does not work.

The api key does not get the custom name specified and is appended to the query string not added to the headers.

**Comment by domaindrivendev** [comment] 2015-04-16 16:55
This is a duplicate of #224 and #222. See the latter for a workaround

**Closed by domaindrivendev** 2015-04-16 16:55 UTC
