### ISSUE TITLE
2 newbie question about having different version documentation

### ISSUE THREAD

**Issue by Iloshka** [domaindrivendev/Swashbuckle#51] opened 2014-06-28 19:23 UTC
Hi,
I implemented in web api 2 versioning based on namespaces,based on http://blogs.msdn.com/b/webdev/archive/2013/03/08/using-namespaces-to-version-web-apis.aspx implementations.
Documentation now generated in root/swwagger.
Is any way to generate documentation in root/v1/swagger? If so, how can i do it?

Also, my web api accessible by root/api/, but your implementation access root/swagger. Is any way to access it by going root/api/swagger?

Thank you

**Comment by domaindrivendev** [comment] 2015-01-19 06:06
This is really an issue with NamespaceHttpControllerSelector because it's implementation of __GetControllerMapping__ breaks the WebApi metadata layer - ApiExplorer, assigning the incorrect paths you've described above. It's one of the reasons why the WebApi team advise against customizing this particular component in the framework:  

http://blogs.msdn.com/b/webdev/archive/2014/08/22/customizing-web-api-controller-selector.aspx

With that said, you can workaround this with a little hackery ... by correcting the generated ApiExplorer before it's passed on to Swashbuckle:

            httpConfig.Services.Replace(typeof(IHttpControllerSelector), new NamespaceHttpControllerSelector(httpConfig));

            var apiExplorer = httpConfig.Services.GetApiExplorer();
            CorrectVersionedPaths(apiExplorer);
        }

        private static void CorrectVersionedPaths(IApiExplorer apiExplorer)
        {
            foreach (var apiDesc in apiExplorer.ApiDescriptions)
            {
                var controllerType = apiDesc.ActionDescriptor.ControllerDescriptor.ControllerType;
                var namespaceParts = controllerType.Namespace.Split(Type.Delimiter);
                var version = namespaceParts.Last();

                apiDesc.RelativePath = new StringBuilder(apiDesc.RelativePath)
                    .Replace(version + ".", "")
                    .Replace("{namespace}", version.ToLower())
                    .ToString();
            }
        }

This will fix the incorrect part of the path. It also replaces the "namespace" route parameter with the actual version, which can be inferred from the controller namespace. With this is done, you can remove the corresponding parameter from the Swagger document because it's value is now hard-coded into the path. This can be done by wiring up a simple IOperationFilter:

   public class RemoveNamespaceParams : IOperationFilter
    {
        public void Apply(Operation operation, DataTypeRegistry dataTypeRegistry, ApiDescription apiDescription)
        {
            operation.Parameters = operation.Parameters.Where(param => param.Name != "namespace").ToArray();
        }
    }

Try it out and let me know how it goes?

**Comment by domaindrivendev** [comment] 2015-01-22 07:29
Closing because the issue is independent of Swashbuckle. It starts in the WebApi metadata layer (ApiExplorer) as a result of replacing the DefaultHttpControllerSelector with a custom version that supports namespaced controllers.

See previous comment for a workaround

**Closed by domaindrivendev** 2015-01-22 07:29 UTC

**Comment by Iloshka** [comment] 2015-02-19 00:12
Hi,
Sorry i was switched from that project. Now im back in.
I installed V5 of Swashbuckle up to documentation.
But i cant make it work, it doesnt expose controller methods.
Do you know what im doing wrong?
Im attaching sample project

Iloshka

**Comment by remster85** [comment] 2017-03-23 19:28
Does the dropdown field listing all the available versions include a redirect action when selected?
It seems to be only for display purposes on my version 5.5.3
