### ISSUE TITLE
Invalid string length

### ISSUE THREAD

**Issue by andrenpt** [domaindrivendev/Swashbuckle#917] opened 2016-10-29 14:14 UTC
I am having troubles to load the documentation using swagger-ui. I suspect that this happens because my json file is huge.

If necessary I can provide the JSON file, for debugging proposes, via private message. 

If you need more information please just let me know.

```
Uncaught RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at t.exports.u.getModelSampleJSON (http://localhost/api/swagger/ui/swagger-ui-min-js:9:748)
    at new t.exports (http://localhost/api/swagger/ui/swagger-ui-min-js:8:26467)
    at http://localhost/api/swagger/ui/swagger-ui-min-js:7:17315
    at r (http://localhost/api/swagger/ui/swagger-ui-min-js:11:12853)
    at Object.forEach (http://localhost/api/swagger/ui/swagger-ui-min-js:11:24144)
    at http://localhost/api/swagger/ui/swagger-ui-min-js:7:17041
    at http://localhost/api/swagger/ui/swagger-ui-min-js:11:22737
    at r (http://localhost/api/swagger/ui/swagger-ui-min-js:11:16261)
    at http://localhost/api/swagger/ui/swagger-ui-min-js:11:22408
```

**Comment by srebella** [comment] 2016-11-02 15:09
this problem may be caused because your json is too large, due to looped entities (entities calling same entities..). I had the same trouble and after fixing it no problem.

**Comment by andrenpt** [comment] 2016-11-03 11:15
Hello @srebella but that is normal. Entities may have other entities as properties.
More specifically how did you solve the problem? 
Did you add any extra configuration ? 
Swashbuckle generates that JSON file.

**Comment by srebella** [comment] 2016-11-03 14:38
yes @andrenpt that is normal.. but sometimes it makes the json huge.. the way to filter the json document is using the DocumentFilter.. check this url and let me know [http://stackoverflow.com/a/31159468/2144426](url)

**Comment by dariusdamalakas** [comment] 2016-11-07 07:30
@andrenpt we use circular reference and it works just fine. I am keen to understand what is the issue, as we depend on swaschbuckle heavily. Would you be able to share your json file? Try renaming definitions and properties, it would be good if you could upload it here.

**Comment by andrenpt** [comment] 2016-11-07 08:47
Hello @dariusdamalakas  I do not mind of sharing the file with you but it needs to be via private message.

**Comment by srebella** [comment] 2016-11-07 13:09
@andrenpt Due to my huge circular references I had to create some special APImodel for the API so the documentator can create the JSON file.

**Comment by dariusdamalakas** [comment] 2016-11-07 13:15
@andrenpt - can you remove that sensitive information?  remove properties / rename, change structure around. I am sure it should be possible to trim that file down a little bit. Otherwise, yes, you can send via private message.

**Comment by andrenpt** [comment] 2016-11-07 14:36
@dariusdamalakas here it is. If you need anything else just tell me please. Thanks
[json.zip](https://github.com/domaindrivendev/Swashbuckle/files/575608/json.zip)

**Comment by dariusdamalakas** [comment] 2016-11-07 14:46
@andrenpt  thanks, but this does not look like a valid swager file.

For example, here what lines 99 to 105 look.   the path "/webs/sometime/" is not defined correctly, it is missing operations, etc.

````
"/webs/someitem/" { "someitemId" }
    "/user/",
    { "userId" },
    : {
      "get": {
        "tags": [
          "web"
````

**Comment by andrenpt** [comment] 2016-11-07 15:19
Sorry about that @dariusdamalakas . Can you please try this one and let me know ?
[json.zip](https://github.com/domaindrivendev/Swashbuckle/files/575717/json.zip)

**Comment by dariusdamalakas** [comment] 2016-11-07 15:51
@andrenpt , that still looks wrong. I've pasted this json here, you should the validation error there.

http://www.jsoneditoronline.org/?id=914441c5039ad57bb3b1d5ab54f32e74

**Comment by dariusdamalakas** [comment] 2016-11-07 15:53
@andrenpt , that still looks wrong. I've pasted this json here, you should the validation error there.

http://www.jsoneditoronline.org/?id=914441c5039ad57bb3b1d5ab54f32e74

**Comment by andrenpt** [comment] 2016-11-07 16:20
Hello @dariusdamalakas 
I have an extension in my browser that was interfering with the JSON. 
Now it should be working perfect. Just tested in the website you gave me to test.
[json.zip](https://github.com/domaindrivendev/Swashbuckle/files/575913/json.zip)

**Comment by andrenpt** [comment] 2016-11-08 21:08
Hello @dariusdamalakas is the file ok now for you ?

Thanks

**Comment by dariusdamalakas** [comment] 2016-11-09 09:02
@andrenpt , yes, that looks better now.  You have duplicate mappings in your swagger file.  `"Company.Software.Part.SomeLayer.Models.Product"` is defined twice under `definitions` section.

I've used [swagger-cli](https://github.com/BigstickCarpet/swagger-cli) to validate this, worked like a charm. 

````
SyntaxError: Error parsing "c:/work/swagger.json"
duplicated mapping key at line 4050, column 4:
                },
       ^
    at Function.ono [as syntax] (C:\Users\ddama\AppData\Roaming\npm\node_modules\swagger-cli\node_modules\swagger-parser\node_modules\ono\lib\index.js:67:20)
    at parse (C:\Users\ddama\AppData\Roaming\npm\node_modules\swagger-cli\node_modules\swagger-parser\node_modules\json-schema-ref-parser\lib\parse.js:47:17)
    at C:\Users\ddama\AppData\Roaming\npm\node_modules\swagger-cli\node_modules\swagger-parser\node_modules\json-schema-ref-parser\lib\read.js:70:23

YAMLException: duplicated mapping key at line 4050, column 4:
                },
       ^

````

**Comment by andrenpt** [comment] 2016-11-10 15:58
Once again @dariusdamalakas  thanks for your answer.

I think this was due to renaming the class names before sending you the .json example.

I have now tested the file using that same swagger-cli and it does not throw any error. However it does not show any success message as well so I am not sure what is going on here.
I am attaching the file to this comment. 
[example.zip](https://github.com/domaindrivendev/Swashbuckle/files/583804/example.zip)

**Comment by andrenpt** [comment] 2016-11-11 21:14
Hello @dariusdamalakas 
Did you manage to reproduce the problem ?

Thanks for all your help with this.

**Comment by dariusdamalakas** [comment] 2016-11-14 08:35
swagger-cli does indeed not finish validating your schema. Can't really help more here. I'd probably start by cleaning up your swagger file.

**Comment by andrenpt** [comment] 2016-11-14 12:49
Hello @dariusdamalakas,
Unfortunately, I will need to abandon this amazing project. I can't spend more time on trying to fix this.

Many thanks for your help! I really appreciate it.

**Comment by heldersepu** [comment] 2017-05-07 14:59
This looks like an issue in SwaggerUI not in Swashbuckle...

**Comment by domaindrivendev** [comment] 2017-09-18 18:06
@andrenpt - I'm going to close this issue for now. If you've confirmed that the Swagger JSON being generated by Swashbuckle is indeed valid Swagger, then I would have to agree with @heldersepu in saying this is really a Swagger UI issue and should be posted to that project.

If you do get a chance to look at this again, and feel it's due to an issue with Swagger that Swashbuckle generates, please feel free to reopen. Thanks

**Closed by domaindrivendev** 2017-09-18 18:06 UTC

**Comment by SanjayKewat** [comment] 2018-10-31 06:10
I got the same Issue on Swagger UI. Error mention below.

swagger-ui-min-js:9 Uncaught RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at t.exports.u.getModelSampleJSON (swagger-ui-min-js:9)
    at new t.exports (swagger-ui-min-js:8)
    at swagger-ui-min-js:7
    at r (swagger-ui-min-js:11)
    at Object.forEach (swagger-ui-min-js:11)
    at swagger-ui-min-js:7
    at swagger-ui-min-js:11
    at r (swagger-ui-min-js:11)
    at swagger-ui-min-js:11

**Comment by SanjayKewat** [comment] 2018-10-31 06:10
please help me, how to solve this issue.

**Comment by SanjayKewat** [comment] 2018-10-31 11:49
I am using nuget package Swashbuckle on MVC Web Api Project.

**Comment by Gawiga** [comment] 2019-12-13 19:39
> yes @andrenpt that is normal.. but sometimes it makes the json huge.. the way to filter the json document is using the DocumentFilter.. check this url and let me know http://stackoverflow.com/a/31159468/2144426

Solved here! 👍
