### ISSUE TITLE
[HttpGet] method with [FromBody] parameter described in swagger doc as "in":"query" instead of "body"

### ISSUE THREAD

**Issue by aparvis** [domaindrivendev/Swashbuckle#716] opened 2016-04-14 16:46 UTC
Hi

Is it deliberate behavior of Swashbuckle to represent [FromBody] parametr in [HttpGet] method as "in":"query"? I think it should be "in":"body". I know it's not recommended to use body parameters in GET requests but it's not forbidden.

Example:
Simple controller:

``` c#
public class DefaultController : ApiController
{
        [HttpGet]
        public string Test([FromBody]string value)
        {
            return value;
        }
}
```

corresponding autogenerated swagger doc excerpt:

``` javascript
"parameters" : [{
        "name" : "value",
        "in" : "query",
        "required" : true,
        "type" : "string"
    }
```

It should rather look like this:

``` javascript
"parameters" : [{
        "name" : "value",
        "in" : "body",
        "required" : true,
        "schema" : {
            "type" : "string"
        }
    }
```

**Comment by domaindrivendev** [comment] 2016-04-19 05:31
Looks like a regression introduced by the fix for above (referenced) issue

**Comment by domaindrivendev** [comment] 2017-09-06 16:34
Fixed by 542c2cdc7ea519e8a35b622f1785ab080ff8e533

**Closed by domaindrivendev** 2017-09-06 16:34 UTC
Labels: waiting for response

**Comment by karthiga117** [comment] 2020-08-14 14:35
In our project we are using Swashbuckle.AspNetCore.Swagger  5.0.0. i am not able to bind the HttpGet with FromBody attribute. I searched for related details in forum. i am getting an error while using it. Is there any option to use FromBody in HttpGet in Swagger 5.0.0

**Comment by juamurex** [comment] 2020-08-26 06:52
The same thing happens in our project. We get an error when using an Attribute + IOperationFilter and also when using the FromBody. We need to send a json with the GET request, to filter the results. The only alternative we see is to do it with parameters in URL but it is a lot of information.
