### ISSUE TITLE
Securing the Swagger JSON & UI 

### ISSUE THREAD

**Issue by RodH257** [domaindrivendev/Swashbuckle#417] opened 2015-07-07 04:31 UTC
I've got an API that will be hosted on the public internet, and I've got authentication setup for the endpoints themselves. I've injected custom javascript into my swagger UI to handle sending these values through, so that all works great, but I want to prevent the general public from seeing my API spec, both the JSON & the HTML file (though perhaps just the JSON is important to secure as the HTML file won't leak anything without it).

Is there a simple way for me to lock down the swagger JSON, perhaps so that I need to enter an API key to see anything?

**Comment by mbeckenbach** [comment] 2015-07-09 08:53
I have a similar issue. My swashbuckle runs inside an mvc 5 app which uses the default asp.net identity login with a cookie. Is it possible to only deliver the ui and json file for a specific user role?

**Comment by joshhendo** [comment] 2015-08-06 23:22
I'm in the same boat - for internal APIs that are hosted publicly, it'd be good if there was a way (maybe just a Basic Auth username and password?) to ensure only developers can access it.

**Comment by domaindrivendev** [comment] 2015-08-17 16:30
This is a duplicate of #384. If you look at that ticket it provides some potential approaches.

**Closed by domaindrivendev** 2015-08-17 16:30 UTC
