### ISSUE TITLE
Multiple versions docs not working

### ISSUE THREAD

**Issue by brgrz** [domaindrivendev/Swashbuckle#328] opened 2015-05-13 18:47 UTC
Similarly to issue https://github.com/domaindrivendev/Swashbuckle/issues/197 I am not seeing docs for all of the versions of my API.

This is what I have:

				c.MultipleApiVersions(
					(apiDesc, targetApiVersion) => ResolveApiVersionsByAttributeRouting(apiDesc, targetApiVersion),
					(vc) =>
					{
						vc.Version("v2", "API v2");
						vc.Version("v1", "API v1");
					});

    public static bool ResolveApiVersionsByAttributeRouting(ApiDescription apiDesc, string targetApiVersion)
    {
      return apiDesc.Route.RouteTemplate.Contains(targetApiVersion);
    }

My routes are attribute routes containing `v1` and `v2` as plain text (within RoutePrefix).

The `ResolveApiVersionsByAttributeRouting` never gets called with `targetApiVersion` set to v1, that is why I only see v2 API docs generated.

**Comment by brgrz** [comment] 2015-05-13 19:21
Also the 

.EnableSwaggerUi(c =>
        {
            c.EnableDiscoveryUrlSelector();
        });

does not render the version selector dropdown (readme states it should).

**Comment by domaindrivendev** [comment] 2015-05-19 07:03
Can't repro any of this in the dummy app.

The lambda not getting called for specific targetApiVersion values sounds like very strange behavior because it's really not reflective of the way the code works. Could you show me your full SwaggerConfig.cs as that may provide some more clues, or at least help me repro.

Thanks

**Comment by domaindrivendev** [comment] 2015-05-21 16:35
Closing for now as I can't repro. Feel free to re-open if you have more details to share.

**Closed by domaindrivendev** 2015-05-21 16:35 UTC

**Comment by daerhiel** [comment] 2016-12-15 09:18
I could reproduce that. @brgrz, you probably customized swagger frontend and modified Index.html or removed some js files. I see from sourcecode that EnableDiscoveryUrlSelector() injects custom js resourse, but I'm not sure where it takes it from. @domaindrivendev, could you advise?
