### ISSUE TITLE
Please add a changelog to the release

### ISSUE THREAD

**Issue by niemyjski** [domaindrivendev/Swashbuckle#264] opened 2015-04-08 18:15 UTC
I'm trying to figure out what all changed in 5.1. Can you please add the release notes to the latest github release.

**Comment by nibras85** [comment] 2015-04-09 14:50
+1

**Comment by nibras85** [comment] 2015-04-09 15:27
Also, after upgrading to 5.1, enabling XML comments broke the Swagger UI

**Comment by domaindrivendev** [comment] 2015-04-13 07:47
Had some issues with Nuget and had to re-release as 5.1.1

I've added some brief release notes to give you an idea of what has changed. It's also worth noting that SB follows semantic versioning - meaning only a major version increment is expected to introduce "breaking changes".

Although, it looks like @nibras85 has possibly stumbled on a regression bug. I can't repro any issues with Xml comments right now. As this issue is specific to release notes, I'm going to close it.

@nibras85 could you create a separate ticket for your issue and elaborate a little more so that I can try repro?

**Closed by domaindrivendev** 2015-04-13 07:47 UTC
