### ISSUE TITLE
Response code as attribute instead of xml comment

### ISSUE THREAD

**Issue by DavidDeSloovere** [domaindrivendev/Swashbuckle#175] opened 2015-01-29 11:12 UTC
I've created some code for a ResponseCodeAttribute and operation filter to go with it.
Personally I like this more than the brittle xml construct for documenting response codes.

I'd be happy to submit a PR if you think this would be a great addition to Swashbuckle core.

It looks like this:

        [ResponseCode(StatusCode = (int)HttpStatusCode.BadRequest, Description = "Value must be greater than zero.")]
        [ResponseCode(StatusCode = (int)HttpStatusCode.PaymentRequired, Description = "Credit balance insufficient.")]

**Comment by domaindrivendev** [comment] 2015-01-29 16:23
Firstly, I agree with you re the brittle use of XML for describing different response codes. It's probably my least favorite feature in SB. But, a lot of people seem to use it so there it is :)

With the exception of ResponseTypeAttribute (which is already provided by WebApi), I've always been reluctant to introduce a whole set of meta-data attributes that affect nothing other than the

**Comment by DavidDeSloovere** [comment] 2015-02-02 11:00
I never thought of the attributes and comments as lifeless noise/markers. You certainly have a point. In the beginning these get created and updates correctly, and after a while they might get out-of-sync. That depends one the dev though.

An extra lib might be a better idea. Who will initiate?

**Comment by domaindrivendev** [comment] 2015-02-02 18:04
If you're interested, I think you should initiate this? I'm happy to refer to it in the main docs.

There's a whole range of operation-level meta-data (response codes, tags, oauth scopes etc..) that could be denoted by these attributes and so a separate project would allow these to be contributed to and released independently of the main project.

I would just have one ask if it's OK with you - that the attribute names are prefixed by "Swagger" so it's clear they're for documentation purposes only.

**Comment by DavidDeSloovere** [comment] 2015-02-05 10:28
Ok. Let's do this.
What shall I call it?

Swashbuckle.Annotations
Swashbuckle.Contrib.Annotations
...

**Comment by domaindrivendev** [comment] 2015-02-10 02:10
Swashbuckle.Annotations sounds good to me

**Comment by domaindrivendev** [comment] 2015-03-17 15:43
@DavidDeSloovere - not sure if you' ve kicked anything off yet but after a series of issues/feature requests around the "inferior" Xml comments approach, I'm thinking maybe this should be added to Core after-all.

**Comment by DavidDeSloovere** [comment] 2015-03-18 07:57
Haven't started yet. Really sorry about that.
So your call: add to core or seperate project?
I've got some time tomorrow.

**Comment by DavidChristiansen** [comment] 2015-03-19 14:11
Watching with interest ;)

**Comment by DavidDeSloovere** [comment] 2015-03-22 12:16
First version is a fact:
https://github.com/DavidDeSloovere/Swashbuckle.Annotations

**Comment by domaindrivendev** [comment] 2015-03-23 19:06
Hey man - nice work getting this going ...

How would you feel about ultimately merging back into the main project as we had briefly discussed above? Despite my original comments and personal preference for keeping documentation-only attributes out of controllers, I'm starting to feel this functionality should be available out-of-the-box. A lot of people appear to to want it!

**Comment by DavidDeSloovere** [comment] 2015-03-24 06:47
To be honest, I would not be happy with merging it back into the core. That's because I wrestled with the project setup and build (myget) for a few hours (on a sunday morning). And all that would have been for nothing. But that personal.
Maybe more important, the package has already been published and I would hate to leave a version 1.0 there forever without a change.
If you want it there by default, you could add it as a dependency to Swashbuckle package itself, it that makes sense. I only take a dependency on Swashbuckle.Core package.
But you own Swashbuckle, so if you want to take it in, you're the boss.

**Comment by DavidDeSloovere** [comment] 2015-03-24 07:41
Giving this some thought on the ride to work, maybe it's best to just integrate this into Swashbuckle.

I can easely remove the github repo and myget feed. 
I have already unlisted the nuget package. Hope not to many people will have installed this already.

**Comment by domaindrivendev** [comment] 2015-03-26 19:41
Hey man - I'm feeling a little bad about this because it was my suggestion to originally separate into a separate package but I thought there was still an outstanding question above as to which way we would go.

Response codes in particular are coming up in more and more issues and I think simple, clean expressive attributes is the best way to solve it. I do think it makes most sense to come out of the box, particularly given the apparent demand. I also want to get this released ASAP so I don't have to keep referring people to the hacky XML docs approach.

Based on you last comment, I'm assuming you're OK with this? If so, do you want to create the PR and I'll merge it in ASAP and be sure to give you some creds in the readme.

Thanks again for all the assistance.

**Comment by DavidDeSloovere** [comment] 2015-03-27 08:35
Two questions for now: in what branch and what namespace do you want these?

**Comment by domaindrivendev** [comment] 2015-03-27 16:36
You can go ahead and create your own feature branch for this - "swagger-annotations" then when you're done just kick off a pull request based on that branch. Then I'll go ahead and merge it in.

Re the namespace, I think Swashbuckle.Swagger.Annotations makes the most sense. So, you'll need to create the corresponding folder in the Swashbuckle.Core project.


I would also suggest no need for the config extension method - just have the filter registered out of the box in the same way it's done for HandleFromUriParams.

Re-opening the issue to track

**Comment by DavidDeSloovere** [comment] 2015-03-28 14:11
I have custom code working, in combination with Swashbuckle 5.0.4 from nuget.

I created a new branch from master and there seem to be a lot of changes: SchemaRegistry > DataTypeRegistry, responses > ResponseMessages, ResponseMessage does not contain description and schema...

So I based my branch off swagger_2.0

**Comment by domaindrivendev** [comment] 2015-04-01 16:33
@DavidDeSloovere - many thanks for pushing this feature through. Just realized a pre-release version (5.1.0-rc1) with the changes. Can you check it out and make sure it all works as expected then I'll release proper and update the docs

    Update-Package Swashbuckle -Pre

**Closed by domaindrivendev** 2015-04-01 16:33 UTC

**Comment by DavidDeSloovere** [comment] 2015-04-02 10:04
Just tried the 5.1.0-rc1 and it looks great ! 
Another win for Swashbuckle.
Btw, Microsoft using swashbuckle for Azure app service... awesome!

**Comment by OnamChilwan** [comment] 2015-04-17 08:12
Hi there guys, sorry might be doing something stupid but I have added the following attribute to an action and when I view the documentation, this type isn't being documented? I am expecting to be shown under "Response Messages" and the column "Response Model" to show the type?

Is there additional config I have missed?

[SwaggerResponse(HttpStatusCode.BadRequest, "Bad Response", typeof(IEnumerable<Error>))]

Should mention I am using version 5.1.3 of Swashbuckle.

Nice work on the extension, like it very much :+1:

**Comment by SandyChapman** [comment] 2015-07-06 11:46
Hey guys,

This improvement works great. Just wanted to say thanks. And for anyone coming to this page looking for annotations using Azure's Web API project template: it is using an outdated version of SB. So go ahead and update your reference to get the new Annotation namespace.

**Comment by easygoingalex** [comment] 2015-10-01 11:08
I too am experiencing an issue with the Response Type. I have specified Exception as being the response type for internal server error (500) using the attributes as follows:

```
[SwaggerResponse(HttpStatusCode.InternalServerError, "Unexpected error.", typeof(Exception))]
```

However the resultant documentation just shows "Object" because SB has generated the following in the definitions section:

```
		"Object": {
			"type": "object",
			"properties": {
				
			}
		},
```

When it should've created:

```
		"Exception": {
			"type": "object",
			"properties": {
				"Data": { "type": "object" },
				"HelpLink": { "type": "string" },
				"HResult": { "type": "integer", "format": "int32" },
				"InnerException": { "type": "object", "schema": "$ref":"#/definitions/Exception"},
				"Message": { "type":"string" },
				"Source": { "type": "string" },
				"StackTrace": { "type": "string" },
				"TargetSite": { "type": "object" }
			}
		},
```

Obviously there would be some cut off in the definition, but when the response comes over the wire, the JSON is adequately formulated as the following:

```
{
  "Message": "There was an unexpected error."
}
```

Is there something I need to do to get Swashbuckle to understand this type?

**Comment by koolraap** [comment] 2016-02-10 23:08
@easygoingalex @OnamChilwan 
I think the issue is that the models you're returning do not have XML documentation for framework classes available to swagger, so it generates an `object` rather than `Exception`.

You can either create your own XML documentation file for the framework classes you need and add that during Swashbuckle configuration, or create an operation filter.
