### ISSUE TITLE
Controller method with custom route parameter type causing operation to be ignored

### ISSUE THREAD

**Issue by tkirchner-clickboarding** [domaindrivendev/Swashbuckle#759] opened 2016-05-12 13:37 UTC
This is a similar issue to #518, however the solution to #518 isn't working for me. 

The issue being that when I use a custom type in my Controller Method's route, the operation does not appear in the swagger page.

`[HttpGet, Route("Api/CustomObjects/{customObject}")]
public async Task<ResponseObject> GetAsync(CustomObject customObject)`

The CustomObject comes in as a string, and is then transformed to the CustomObject type in an HttpParameterBinding. The functionality that I'm looking for as far as the Api goes is working correctly, the swagger document generated by Swashbuckle just isn't showing this operation.

The only differences between this issue and #518 are that I am registering my HttpParameterBinding through the config and am not using it as an attribute. I cannot / do not want to use an attribute because I need to provide additional constructor arguments to the Binding. Any help would be greately appreciated.

Using Swashbuckle 5.2.2

`public class CustomObjectParameterBinding : HttpParameterBinding, IValueProviderParameterBinding
{
    private readonly IValue2Provider _value2Provider;

```
public CustomObjectParameterBinding(HttpParameterDescriptor descriptor, IValue2Provider value2Provider) : base(descriptor)
{
    _value2Provider = value2Provider;
}

public IEnumerable<ValueProviderFactory> ValueProviderFactories
{
    get
    {
        return new List<ValueProviderFactory> { new RouteDataValueProviderFactory() };
    }
}

public override async Task ExecuteBindingAsync(ModelMetadataProvider metadataProvider, HttpActionContext actionContext, CancellationToken cancellationToken)
{
    var rawValue = actionContext.RequestContext.RouteData.Values[Descriptor.ParameterName];

    var value1 = rawValue as string;
    var value2 = await _value2Provider.ProvideAsync(value1);

    var customObject = new CustomObject
    {
        Value1 = value1,
        Value2 = value2,
    };

    SetValue(actionContext, customObject);
}
```

}`
The parameter binding is registered using

`...
config.ParameterBindingRules.Insert(0, typeof(CustomObject), descriptor => new CustomObjectParameterBinding(descriptor, value2Provider));
...`

**Comment by domaindrivendev** [comment] 2016-08-09 16:24
Hi there. Although this appears similar to #518, I think the root cause is very different. Unfortunately, this appears to be a known bug with the ApiExplorer - the WebApi component that SB uses to obtain all ApiDescriptions, which it then transforms into Swagger Operation descriptions. See the following:

http://forums.asp.net/t/1835575.aspx?ApiExplorer+and+parameters+of+complex+type

The only workaround I can offer right now, is to wire up a Document Filter (see readme) that manually adds a description for that operation. If you're going to do this, I would recommend reading the swagger-spec first: http://swagger.io/specification/

**Comment by domaindrivendev** [comment] 2017-09-14 18:16
If you look at the ASP.NET link I provided above, it doesn't look like the underlying `ApiExplorer` issue is going to be addressed any time soon, if at all. So, you're really stuck with the `DocumentFilter` workaround to just add the missing operation description.

However, I can confirm that the specific issue is addressed in ASP.NET Core. However, there now appears to be other issues with your scenario. I've captured these new issues in the Core-specific Swashbuckle project:

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/488

**Closed by domaindrivendev** 2017-09-14 18:16 UTC

**Comment by razonrus** [comment] 2017-11-05 16:51
It is not a Swagger problem. After correct settings for standart ApiExplorer all must work.
Similar question: https://stackoverflow.com/questions/46788440/route-with-custom-type-doesnt-show-up-in-swagger
Example with my solution: https://stackoverflow.com/a/47123965/908936
