### ISSUE TITLE
Sample code to use swashbuckle with already IIS deployed web api

### ISSUE THREAD

**Issue by ravi032** [domaindrivendev/Swashbuckle#389] opened 2015-06-10 16:07 UTC
Could you please help me with sample swashbuckle code [if it supports]. We have deployed web api on IIS and scenario is I could not able to integrate it in web api code and build it.

Thanks in advance.

**Comment by domaindrivendev** [comment] 2015-06-10 16:22
Please, can I ask that you stop opening issues which are duplicates of ones you previously created

#349, #358 

In my responses to these, I've referenced yet another duplicate of this issue and provided some guidelines there #356. With time constraints, that's the best I can do for now, you'll have to dig deeper yourself.

**Closed by domaindrivendev** 2015-06-10 16:22 UTC

**Comment by ravi032** [comment] 2015-06-10 16:24
ok
