### ISSUE TITLE
Multiline XML comments create EOL characters in Swagger spec

### ISSUE THREAD

**Issue by Snelbinder** [domaindrivendev/Swashbuckle#323] opened 2015-05-12 13:07 UTC
When I write comments for a property of a complex type which is a parameter for a route, I sometimes write multiple lines in the summary, like this:
```
        /// <summary>
        /// Specification for languages, for example "nl" or "en". Multiple 
        /// languages can be specified. If not set, default language will 
        /// be returned.
        /// </summary>
        public string[] LanguageCodes { get; set; }
```
This will create the following XML output:
```
        <member name="P:Api.Parameters.ServiceRequestContextParams.LanguageCodes">
            <summary>
            Specification for languages, for example "nl" or "en". Multiple 
            languages can be specified. If not set, default language will 
            be returned.
            </summary>
        </member>
```
This is fine, but in the swagger spec this is translated as follows:
```
{
    "name": "languagecodes",
    "in": "query",
    "description": "Specification for languages, for example \"nl\" or \"en\". Multiple \r\n            languages can be specified. If not set, default language will \r\n            be returned.",
    "required": false,
    "type": "array",
    "items": {
    "type": "string"
}
```
Swagger-codegen fails because of the EOL characters. Any suggestions?

**Comment by domaindrivendev** [comment] 2015-05-12 20:28
Closing as this is a duplicate of #82

As noted, you can create an IOperationFilter that escapes new lines automatically. This may get added out-of-the-box in a future version. Keep an eye here for updates - #258

**Closed by domaindrivendev** 2015-05-12 20:28 UTC
