### ISSUE TITLE
Ability to hide fields and/or API from documentation

### ISSUE THREAD

**Issue by bugnuker** [domaindrivendev/Swashbuckle#178] opened 2015-02-05 15:39 UTC
I am trying to hide some API's and maybe even some fields from documentation.

I can't figure out how to hide them except using the Obsolete Attribute but this make the API invalid as well.

The swagger-UI supports it it seems: https://groups.google.com/forum/#!topic/swagger-swaggersocket/LgrU5ecwcoE

How can I support this in WEB API?

Thanks!

**Comment by domaindrivendev** [comment] 2015-02-05 17:28
This is a duplicate of #153.

Re individual fields, if you don't want to document them then I assume they're only present on the class for internal use? If this is the case, just mark them internal instead of public and Swashbuckle will ignore them.

If you really do need them to be public but don't want to document them, there are other options I can share. First though, I'd like to understand your use-case a little better - the only valid reason I can think of for exposing a property in your API but hiding it in your API docs would be if it's obsolete.

**Closed by domaindrivendev** 2015-02-05 17:28 UTC

**Comment by bugnuker** [comment] 2015-02-05 18:54
Than you so much. I tried to find this my self but I was unable to.

As for fields... the issue is pretty crazy, but I have some fields that are only used for official APP's and would rather not display them to end users so they don't get confused.

I'll figure something out ;)

Thanks again!!

**Comment by docandys** [comment] 2015-02-12 11:05
Hi domaindrivendev,
You say above you can't think of a use case for not displaying swagger info for an API. I have a site that has web services that are for customer use and another web service that responds to requests from my billing service. Although this other service is protected in various ways so that it can't be spoofed I don't want to document it - it encourages people to play and distracts from the goodies.

Andy

**Comment by JiaJian** [comment] 2015-07-15 16:53
@docandys can confirm this works! Have been trying to look for a solution for ages.

**Comment by wooderz** [comment] 2017-11-07 15:00
An example would be an Id property that you populate internally to facilitate in update or an insert - that you don't want provided by the client.

I want to have the Id on my model, but not in the documentation. I can't mark it as internal as the Id is used by other things (queries and the like). It's not obsolete at all - I just want to hide it

**Comment by heldersepu** [comment] 2017-11-07 15:06
@wooderz  Look into document filters, I have a few examples here:
https://github.com/heldersepu/SwashbuckleTest/blob/master/Swagger_Test/App_Start/SwaggerConfig.cs#L323
you can do exactly that with one of those

**Comment by wooderz** [comment] 2017-11-07 15:12
@heldersepu I'm not sure that will help? It'll be for all models etc then? We want it only for certain models... would be great to be able to write an attribute that swashbuckle will then use to hide or not a property

**Comment by heldersepu** [comment] 2017-11-07 15:41
@wooderz Please provide a project with the models and I will help you out.
I'm sure there is a pattern we can identify...

**Comment by wooderz** [comment] 2017-11-07 15:48
@heldersepu something along the lines of

```
public async Task<IHttpActionResult> Put(NewUserWriteModel newUser)
{
    newUser.Id = Guid.NewGuid();
    await _messageBusSender.PostMessage<NewUserWriteModel>(newUser);

    return Ok();
}
```

With NewUserWriteModel being
```
public class NewUserWriteModel
{
    [SomeAttributeHereToOnlyIgnoreInSwagger]
    public Guid Id { get; set; }
    public string Email {get; set; }
}
```

We can't use [JsonIgnore] because when it's serialised through MassTransit we lose the Id.

**Comment by heldersepu** [comment] 2017-11-07 15:50
That is just one model, if that is all you have a document filter will be very simple!

**Comment by wooderz** [comment] 2017-11-07 16:28
That's one example. We have 100s of similar models we'd like to do the same to. Hence an attribute would be really useful

**Comment by heldersepu** [comment] 2017-11-07 16:32
Similar models...  you mean all with `public Guid Id` that all need to hide? that is easy

**Comment by mbprocede** [comment] 2017-12-21 18:12
Here is a cleaner solution that I wrote for the AspNetCore Swashbuckle:

```
        public void Apply(SwaggerDocument swaggerDoc, DocumentFilterContext context)
        {
            foreach (var definition in swaggerDoc.Definitions)
            {
                var type = Type.GetType("**NameSpace**." + definition.Key + ",**AssemblyName**");
                if (type != null)
                {
                    var properties = type.GetProperties();
                    foreach (var prop in properties)
                    {
                        var ignoreAttribute = prop.GetCustomAttribute(typeof(SwaggerIgnoreAttribute), false);
                        if (ignoreAttribute != null)
                            definition.Value.Properties.Remove(prop.Name);
                    }
                }
            }
        }
```

You'll need to replace the Namespace and the AssemblyName with your namespace and dll name, as well as create a custom attribute:

`public class SwaggerIgnoreAttribute : Attribute { }`

Decorate the member you wish to hide with the attribute and you are good to go.

**Comment by heldersepu** [comment] 2017-12-21 19:19
It's worth noting @mbprocede  implementation uses reflection and the calls:
`
Type.GetType("**NameSpace**." + definition.Key + ",**AssemblyName**");
type.GetProperties();
prop.GetCustomAttribute(typeof(SwaggerIgnoreAttribute), false);
`
Could be very time consuming if your project is large. 
If you project is large and swagger receives a lot of traffic consider using some caching

**Comment by andrecarlucci** [comment] 2018-02-20 02:05
I created my filter in the same way @heldersepu did, but with a better name for my purposes:

```cs
public class HideStuffDocumentFilter : IDocumentFilter {
        public void Apply(SwaggerDocument swaggerDoc, DocumentFilterContext context) {
            foreach (var definition in swaggerDoc.Definitions) {
                foreach (var prop in definition.Value.Properties.ToList()) {
                    if (prop.Value.MaxLength == int.MaxValue) {
                        definition.Value.Properties.Remove(prop);
                    }
                }
            }
        }
    }
```

and my attribute (here is the trick, extend the attribute):

```cs
    public class ApiIgnoreAttribute : MaxLengthAttribute {
        public ApiIgnoreAttribute() : base(int.MaxValue) {
        }
    }

```

Then just decorate your models:
```cs
public class BillPost {
        [ApiIgnore]
        public string SdpId { get; set; }
        [ApiIgnore]
        public string Provider { get; set; }
        ...
}
```

It works just fine and no reflection :)

**Comment by syaifulnizamyahya** [comment] 2018-03-30 02:53
@andrecarlucci Does this work for asp.net core? Tried, but unsuccessful.

This are the error. System.InvalidCastException: Unable to cast object of type &#x27;System.Int32&#x27; to type &#x27;System.Array&#x27;.&#xD;&#xA;

**Comment by JasonLoKiSmith** [comment] 2018-11-27 06:49
Based on the answer from @mbprocede (Thank you so much!) 
I have slightly improved it so that the namespace does not have to be known. This solution works in .NET framework 4.7.1. It will most likely work in other versions of .NET too as well as .NET Core.

    
```
public class SwaggerDocumentCustomIgnoreFilter : IDocumentFilter
    {
        public void Apply(SwaggerDocument swaggerDoc, SchemaRegistry schemaRegistry, IApiExplorer apiExplorer)
        {
            List<Type> AllTypes = Assembly.GetAssembly(typeof(SwaggerDocumentCustomIgnoreFilter)).GetTypes().ToList();
            foreach (var definition in swaggerDoc.definitions)
            {
              
                var type = AllTypes.FirstOrDefault(x => x.Name == definition.Key);
                if (type != null)
                {
                    var properties = type.GetProperties();
                    foreach (var prop in properties)
                    {
                        var ignoreAttribute = prop.GetCustomAttribute(typeof(SwaggerIgnoreAttribute), false);
                        if (ignoreAttribute != null)
                        {
                            definition.Value.properties = definition.Value.properties
                                                          .Where(x => !string.IsNullOrWhiteSpace(x.Key) && !x.Key.Equals(prop.Name, StringComparison.OrdinalIgnoreCase))
                                                          .ToDictionary(x => x.Key, x => x.Value);
                        }
                    }
                }
            }
        }
    }
```
```

**Comment by xts-velkumars** [comment] 2019-09-27 12:20
@JasonLoKiSmith 
I'm trying to remove, but its not removing from the list. Any clue?

**Comment by DanielCaspers** [comment] 2019-10-25 01:21
@JasonLoKiSmith inspired me to write a slightly different solution based on my needs. 

This was written in .NET Core 2.2, but I can also see this working in .NET Framework with minimal modification.

	public sealed class SwaggerDocumentCustomIgnoreFilter : IDocumentFilter
	{
		public void Apply(SwaggerDocument swaggerDoc, DocumentFilterContext context)
		{
			List<Type> allTypes = AppDomain.CurrentDomain.GetAssemblies()
				.SelectMany(a => a.GetTypes())
				.ToList();

			List<Type> allTypesWithAttribute = allTypes
				.Where(t => t.GetCustomAttributes(true).OfType<SwaggerDocumentCustomIgnoreAttribute>().Any())
				.ToList();

			foreach (Type type in allTypesWithAttribute)
			{
				swaggerDoc.Definitions.Remove(type.Name);
			}
		}
	}

**Comment by Nathalino** [comment] 2020-02-09 00:53
And how do I remove only the model, without impacting the actions of the controler. I observe the withdrawal of attributes from the model a lot, but if you want to remove the model from the documentation.

technology employed:
I use Swashbuckle.AspNetCore v3.0.0 / Swagger-Ui v3.17.1

Thank you very much in advance
